title: My Jekyll Site
description: >- # this means to ignore newlines until "baseurl:"
  This is a sample description of my Jekyll site.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://username.github.io" # the base hostname & protocol for your site
theme: minima

# Build settings
markdown: kramdown
